services:
  - type: web
    name: face-recognition-service
    runtime: python
    plan: free  # Tambahkan ini agar otomatis memilih paket gratis
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: API_SECRET
        generateValue: true
      - key: FACE_DISTANCE_THRESHOLD
        value: "0.5"
      - key: BLUR_THRESHOLD
        value: "80.0"
      - key: PYTHON_VERSION
        value: "3.11.0"